spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: 1111
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      format_sql: true
      jdbc:
        lob:
          non_contextual_creation: true